var data = {
    'Chandigarh': { confirmed: 91, active: 83, recovered: 5, deceased: 3 },
    'Delhi': { confirmed: 197, active: 89, recovered: 6, deceased: 2 },
    'Himachal Pradesh': { confirmed: 85, active: 79, recovered: 5, deceased: 1 },
    'Haryana': { confirmed: 85, active: 79, recovered: 5, deceased: 1 },
    'Jammu and Kashmir': { confirmed: 65, active: 79, recovered: 5, deceased: 1 },
    'Andhra Pradesh': { confirmed: 96, active: 79, recovered: 5, deceased: 1 },
    'Kerala': { confirmed: 285, active: 79, recovered: 5, deceased: 1 },
    'Lakshadweep': { confirmed: 127, active: 79, recovered: 5, deceased: 1 },
    'Orissa': { confirmed: 46, active: 79, recovered: 5, deceased: 1 },
    'Dadra and Nagar Haveli': { confirmed: 85, active: 79, recovered: 5, deceased: 1 },
    'Karnataka': { confirmed: 141, active: 83, recovered: 5, deceased: 3 },
    'Maharashtra': { confirmed: 220, active: 171, recovered: 39, deceased: 10 },
    'Andaman and Nicobar': { confirmed: 116, active: 109, recovered: 6, deceased: 1 },
    'Assam': { confirmed: 96, active: 79, recovered: 17, deceased: 10 },
    'Manipur': { confirmed: 116, active: 109, recovered: 6, deceased: 1 },
    'Nagaland': { confirmed: 96, active: 79, recovered: 17, deceased: 10 },
    'Meghalaya': { confirmed: 196, active: 179, recovered: 10, deceased: 9 },
    'Punjab': { confirmed: 246, active: 79, recovered: 17, deceased: 10 },
    'Rajasthan': { confirmed: 126, active: 100, recovered: 26, deceased: 0 },
    'Uttar Pradesh': { confirmed: 236, active: 79, recovered: 17, deceased: 10 },
    'Uttaranchal': { confirmed: 91, active: 83, recovered: 5, deceased: 3 },
    'Jharkhand': { confirmed: 96, active: 79, recovered: 17, deceased: 10 },
    'West Bengal': { confirmed: 185, active: 179, recovered: 5, deceased: 1 },
    'Bihar': { confirmed: 85, active: 79, recovered: 5, deceased: 1 },
    'Sikkim': { confirmed: 146, active: 79, recovered: 17, deceased: 10 },
    'Chhattisgarh': { confirmed: 96, active: 79, recovered: 17, deceased: 10 },
    'Madhya Pradesh': { confirmed: 91, active: 83, recovered: 5, deceased: 3 },
    'Puducherry': { confirmed: 56, active: 39, recovered: 15, deceased: 2 },
    'Tamil Nadu': { confirmed: 96, active: 79, recovered: 17, deceased: 10 },
    'Gujarat': { confirmed: 56, active: 39, recovered: 15, deceased: 2 },
    'Goa': { confirmed: 96, active: 79, recovered: 17, deceased: 10 },
    'Arunachal Pradesh': { confirmed: 85, active: 79, recovered: 5, deceased: 1 },
    'Mizoram': { confirmed: 96, active: 79, recovered: 17, deceased: 10 },
    'Tripura': { confirmed: 56, active: 39, recovered: 15, deceased: 2 },
    'Daman and Diu': { confirmed: 96, active: 79, recovered: 17, deceased: 10 },
}